// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeHNM7ioQS2Zm1OfBxmiwqWnLKDiF3CVU',
    appId: '1:617312307147:web:bb23a01269fa6df74e584e',
    messagingSenderId: '617312307147',
    projectId: 'e-commarce-iti',
    authDomain: 'e-commarce-iti.firebaseapp.com',
    storageBucket: 'e-commarce-iti.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV2PjmvtlKacwnviZy6SUtL5JCZ1O7EZ4',
    appId: '1:617312307147:android:8f8e1677869a51ca4e584e',
    messagingSenderId: '617312307147',
    projectId: 'e-commarce-iti',
    storageBucket: 'e-commarce-iti.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeLHbGrjHTISiQfZUzyt5r4lNBunzMTrg',
    appId: '1:617312307147:ios:da159f6af51bcce24e584e',
    messagingSenderId: '617312307147',
    projectId: 'e-commarce-iti',
    storageBucket: 'e-commarce-iti.appspot.com',
    iosClientId: '617312307147-pavl3l2g95qt25ss63fr4at50909v9ug.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCommarce',
  );
}
